//! Phase 6 regression guard — the pinned v1 audit-log fixture.
//!
//! `tests/fixtures/audit_v1_pinned.jsonl` was generated by `gen_v1_fixture.rs`
//! against the pre-Phase-6 (v1-only) code and checked in verbatim. Phase 6
//! reshapes the audit log into 16 independently-chained shards with a Merkle
//! anchor, and the single largest risk in that change is silently breaking the
//! ability to verify logs written by an earlier build — a regression that would
//! be invisible in any test that writes and reads with the same code.
//!
//! These tests are the guard: a real v1 file, produced by code that predates
//! every Phase 6 line, must still verify, and a one-character tamper in it must
//! still be caught. Do NOT regenerate the fixture to make a failure go away —
//! a failure here means v1 compatibility broke, which is the finding.

use std::time::Duration;

/// The exact secret `gen_v1_fixture.rs` signed the fixture with.
const FIXTURE_SECRET: &[u8] = b"pinned-v1-fixture-issuer-secret!";

fn fixture_paths() -> (std::path::PathBuf, std::path::PathBuf) {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    (
        dir.join("audit_v1_pinned.jsonl"),
        dir.join("audit_v1_pinned.sentinel"),
    )
}

/// Copy the pinned fixture into a scratch dir so a test never mutates the
/// checked-in file, optionally applying `mutate` to the log contents first.
fn staged_copy(tag: &str, mutate: impl FnOnce(String) -> String) -> (std::path::PathBuf, std::path::PathBuf) {
    let (src_log, src_sentinel) = fixture_paths();
    let content = std::fs::read_to_string(&src_log).expect("pinned fixture must exist");
    let sentinel = std::fs::read_to_string(&src_sentinel).expect("pinned sentinel must exist");

    let scratch = std::env::temp_dir().join(format!("saacp_v1_fixture_{tag}_{}", std::process::id()));
    std::fs::create_dir_all(&scratch).unwrap();
    let log = scratch.join("audit.jsonl");
    let sent = scratch.join("audit.sentinel");
    std::fs::write(&log, mutate(content)).unwrap();
    std::fs::write(&sent, sentinel).unwrap();
    (log, sent)
}

/// A v1 log written before Phase 6 existed must still verify afterwards.
///
/// This is the compatibility contract in its entirety: same bytes, same
/// secret, same verdict.
#[test]
fn pinned_v1_log_still_verifies_after_sharding() {
    let (log, sentinel) = staged_copy("ok", |c| c);
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    assert!(
        audit.verify_chain_disk(FIXTURE_SECRET),
        "the checked-in pre-Phase-6 v1 audit log must still verify — if this fails, \
         v1 backward compatibility is broken (do not regenerate the fixture)",
    );
}

/// `initialize_chain` must accept the pinned v1 file and adopt its state
/// (50 events), not reset to genesis. This is the upgrade path an existing
/// deployment actually takes on restart.
#[test]
fn pinned_v1_log_loads_through_initialize_chain() {
    let (log, sentinel) = staged_copy("init", |c| c);
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    audit
        .initialize_chain(FIXTURE_SECRET)
        .expect("a valid v1 log must load without resetting the chain");
    assert_eq!(
        audit.event_count(),
        50,
        "initialize_chain must adopt the v1 file's event count",
    );
}

/// A tampered v1 log must still be rejected. Without this, the test above
/// could pass with a `verify_chain_disk` that had been reduced to `true`.
#[test]
fn tampered_pinned_v1_log_is_rejected() {
    // Flip one character inside the first record's intent. The HMAC covers it,
    // so the recomputed chain_hash must no longer match.
    let (log, sentinel) = staged_copy("tampered", |c| c.replacen("intent-number-0", "intent-number-9", 1));
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    assert!(
        !audit.verify_chain_disk(FIXTURE_SECRET),
        "a single-character edit inside an HMAC-covered field must be detected",
    );
}

/// Truncating the tail of a v1 log must be caught by the sentinel check
/// (disk_count < sentinel), not silently accepted as a shorter valid chain.
#[test]
fn truncated_pinned_v1_log_is_rejected() {
    let (log, sentinel) = staged_copy("truncated", |c| {
        let lines: Vec<&str> = c.lines().collect();
        lines[..lines.len() - 10].join("\n") + "\n"
    });
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    assert!(
        !audit.verify_chain_disk(FIXTURE_SECRET),
        "dropping the last 10 entries must fail the sentinel count check",
    );
}

/// Verifying with the wrong secret must fail — confirms the fixture's HMACs are
/// genuinely key-bound rather than structurally self-consistent.
#[test]
fn pinned_v1_log_rejects_wrong_secret() {
    let (log, sentinel) = staged_copy("wrongkey", |c| c);
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    assert!(
        !audit.verify_chain_disk(b"a-completely-different-secret!!!"),
        "chain verification must be bound to the issuer secret",
    );
}

/// Appending to a loaded v1 log must produce a file that still verifies end to
/// end. Post-Phase-6 this exercises the v1 -> v2 migration boundary: the new
/// records must anchor to the final v1 hash, not restart at genesis.
#[test]
fn appending_to_a_loaded_v1_log_keeps_the_whole_file_verifiable() {
    let (log, sentinel) = staged_copy("append", |c| c);
    let audit = saacp::security::ImmutableAuditLog::with_paths(
        log.to_str().unwrap(),
        sentinel.to_str().unwrap(),
    );
    audit.initialize_chain(FIXTURE_SECRET).expect("v1 log must load");

    for i in 0..25u32 {
        audit.append_event(
            FIXTURE_SECRET,
            &format!("post-upgrade-src-{i}"),
            &format!("post-upgrade-dst-{i}"),
            "sig-new",
            &format!("appended-after-upgrade-{i}"),
            "",
        );
    }
    assert!(audit.flush(Duration::from_secs(5)), "WAL flush must ack");
    assert!(
        audit.verify_chain_disk(FIXTURE_SECRET),
        "a v1 log extended with newly-appended records must verify across the \
         version boundary — the new region has to chain onto the final v1 hash",
    );
    assert_eq!(audit.event_count(), 75);
}
