//! Hardware Attestation Module
//!
//! Implements TPM/HSM/TEE attestation verification for SAACP.
//! Provides cryptographic proof that a peer is running approved code
//! on trusted hardware before session establishment.
//!
//! # Attestation Types
//! - **TPM 2.0**: TPM quote verification via PCR values
//! - **HSM**: PKCS#11-based key attestation
//! - **TEE/Enclave**: Intel SGX / ARM TrustZone attestation
//!
//! # Security Properties
//! - Prevents session establishment with untrusted hardware
//! - Binds cryptographic identity to hardware root of trust
//! - Enables compliance with healthcare/banking hardware requirements

use std::sync::Arc;

use arc_swap::ArcSwap;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};

use crate::pqc::domain_separation;
use crate::pqc::max_sizes;
use crate::pqc::PqcError;

/// Attestation verification result.
#[derive(Debug, Clone)]
pub struct AttestationVerification {
    /// Whether the attestation is valid.
    pub is_valid: bool,
    /// The attestation type verified.
    pub attestation_type: AttestationType,
    /// Measurement (PCR values / enclave hash) that was verified.
    pub measurement: Vec<u8>,
    /// Timestamp of the attestation.
    pub timestamp: f64,
    /// Human-readable verification details.
    pub details: String,
}

/// Attestation types supported by SAACP.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttestationType {
    /// No attestation (software-only, no hardware root of trust).
    None,
    /// TPM 2.0 quote attestation.
    Tpm,
    /// HSM key attestation via PKCS#11.
    Hsm,
    /// Trusted Execution Environment (TEE).
    Tee,
    /// Secure Enclave (Intel SGX, ARM TrustZone, Apple Secure Enclave).
    Enclave,
}

impl AttestationType {
    /// String representation.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Tpm => "tpm",
            Self::Hsm => "hsm",
            Self::Tee => "tee",
            Self::Enclave => "enclave",
        }
    }

    /// Parse from string.
    ///
    /// Deliberately an inherent method (Python-parity shape), not a `FromStr`
    /// impl â€” see `cluster.rs`'s matching `#[allow]` for the rationale.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "none" => Some(Self::None),
            "tpm" => Some(Self::Tpm),
            "hsm" => Some(Self::Hsm),
            "tee" => Some(Self::Tee),
            "enclave" => Some(Self::Enclave),
            _ => None,
        }
    }

    /// Whether this attestation type requires hardware.
    pub fn requires_hardware(&self) -> bool {
        !matches!(self, Self::None)
    }

    /// Whether this attestation type has a production implementation.
    pub fn is_implemented(&self) -> bool {
        matches!(self, Self::None | Self::Tpm | Self::Hsm | Self::Tee | Self::Enclave)
    }
}

/// TPM 2.0 attestation quote.
#[derive(Debug, Clone)]
pub struct TpmQuote {
    /// TPM quote structure (PCR values, signature).
    pub quote_data: Vec<u8>,
    /// Platform Configuration Register values.
    pub pcr_values: Vec<u8>,
    /// TPM signature over the quote.
    pub signature: Vec<u8>,
    /// AIK (Attestation Identity Key) public key.
    pub aik_public: Vec<u8>,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the quote was generated by the TPM.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// HSM attestation via PKCS#11.
///
/// All fields are parity with [`TpmQuote`] and [`TeeAttestation`]: a real
/// HSM attestation includes a manufacturer certificate chain, a key attestation
/// structure signed by the HSM manufacturer's signing key, and the same
/// freshness-binding fields (nonce / channel_binding / suite_transcript_hash)
/// that bind the quote to this specific session and prevent replay.
#[derive(Debug, Clone)]
pub struct HsmAttestation {
    /// PKCS#11 token label (informational, not security-critical).
    pub token_label: String,
    /// Key attestation structure from the HSM firmware.
    pub key_attestation: Vec<u8>,
    /// HSM manufacturer certificate chain (DER-encoded). Presence is
    /// validated but not chain-verified (requires platform CA trust store).
    pub manufacturer_cert: Vec<u8>,
    /// HSM manufacturer's Ed25519 signing key (32 bytes, raw compressed point).
    /// Used to verify `signature` over [`Self::key_attestation`] and freshness fields.
    pub signing_public_key: Vec<u8>,
    /// Ed25519 signature over the attestation digest (see
    /// [`AttestationVerifier::compute_hsm_attestation_digest`]).
    pub signature: Vec<u8>,
    /// Freshness nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// Suite transcript hash (binds quote to this key negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// Unix timestamp (seconds) when the HSM generated this attestation.
    /// A value of `0.0` means no timestamp was provided and the age check is skipped.
    pub quote_timestamp: f64,
}

/// TEE/Enclave attestation report.
#[derive(Debug, Clone)]
pub struct TeeAttestation {
    /// Enclave measurement (MRENCLAVE / MRMEASUREMENT).
    pub measurement: Vec<u8>,
    /// Attestation report data bound into the report digest.
    pub report_data: Vec<u8>,
    /// Signature over the report digest (see `AttestationVerifier::compute_tee_report_digest`).
    pub signature: Vec<u8>,
    /// TEE type identifier (e.g. "sgx", "trustzone", "sev").
    pub tee_type: String,
    /// Public key used to verify `signature`.
    ///
    /// For Intel SGX ECDSA: the quoting enclave's Ed25519 attestation key.
    /// For ARM TrustZone: the TEE manufacturer's Ed25519 signing key.
    /// Must be exactly 32 bytes (raw Ed25519 compressed point).
    pub signing_public_key: Vec<u8>,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the attestation was generated.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// Attestation evidence that can be verified.
#[derive(Debug, Clone)]
pub enum AttestationEvidence {
    /// No evidence (software-only).
    None,
    /// TPM quote evidence.
    Tpm(TpmQuote),
    /// HSM attestation evidence.
    Hsm(HsmAttestation),
    /// TEE/Enclave attestation evidence.
    Tee(TeeAttestation),
}

/// Snapshot of all trusted signing keys and measurements.
///
/// Stored behind `ArcSwap` so live reloads (via [`AttestationVerifier::update_roots`])
/// are lock-free on the read path and atomic â€” in-flight verifications using the old
/// bundle complete naturally; new ones start with the updated bundle.
#[derive(Clone)]
pub struct TrustedRootBundle {
    /// Trusted measurements (PCR values, enclave hashes) indexed by attestation type.
    pub measurements: Vec<(AttestationType, Vec<u8>)>,
    /// Trusted Ed25519 signing keys indexed by attestation type.
    /// Loaded from a TOML/JSON roots file and verified against the CA signature.
    pub signing_keys: Vec<(AttestationType, VerifyingKey)>,
    /// Monotonically increasing bundle version for diagnostic logging.
    pub version: u64,
}

impl TrustedRootBundle {
    pub fn new() -> Self {
        Self { measurements: Vec::new(), signing_keys: Vec::new(), version: 0 }
    }
}

impl Default for TrustedRootBundle {
    fn default() -> Self { Self::new() }
}

/// Attestation verifier for hardware root of trust.
///
/// Trusted signing keys and measurements are stored in an `ArcSwap<TrustedRootBundle>`
/// so they can be reloaded at runtime (via [`Self::update_roots`]) without restarting
/// the process. The read path is lock-free â€” `self.roots.load()` is an atomic pointer
/// load with no contention.
pub struct AttestationVerifier {
    /// Lock-free, hot-reloadable trusted root bundle.
    roots: ArcSwap<TrustedRootBundle>,
    /// Maximum age of an attestation quote (seconds).
    max_quote_age: f64,
}

impl AttestationVerifier {
    /// Create a new attestation verifier with an empty trusted root bundle.
    pub fn new() -> Self {
        Self {
            roots: ArcSwap::new(Arc::new(TrustedRootBundle::new())),
            max_quote_age: 300.0, // 5 minutes
        }
    }

    /// Create with custom max quote age.
    pub fn with_max_quote_age(max_age: f64) -> Self {
        Self {
            roots: ArcSwap::new(Arc::new(TrustedRootBundle::new())),
            max_quote_age: max_age,
        }
    }

    /// Atomically swap in a new root bundle.
    ///
    /// In-flight verifications using the old bundle complete naturally.
    /// New verifications immediately see the updated keys and measurements.
    /// Safe to call from any thread â€” `ArcSwap::store` is lock-free.
    pub fn update_roots(&self, new_bundle: TrustedRootBundle) {
        let version = new_bundle.version;
        self.roots.store(Arc::new(new_bundle));
        tracing::info!(bundle_version = version, "AttestationVerifier: trusted root bundle updated");
    }

    /// Register a trusted measurement for verification.
    ///
    /// Builds a new bundle from the current one with the measurement appended
    /// and atomically swaps it in. For initial setup; prefer `update_roots` for
    /// bulk changes (avoids N atomic swaps).
    pub fn register_trusted_measurement(
        &self,
        att_type: AttestationType,
        measurement: Vec<u8>,
    ) {
        let old = self.roots.load();
        let mut new_bundle = (**old).clone();
        new_bundle.measurements.push((att_type, measurement));
        new_bundle.version += 1;
        self.roots.store(Arc::new(new_bundle));
    }

    /// Register an Ed25519 attestation signing key for one hardware type.
    ///
    /// Verification is fail-closed: a mathematically valid signature from a key
    /// that is not present in this registry is not trusted. Prefer loading a
    /// complete [`TrustedRootBundle`] with [`Self::update_roots`] for startup
    /// configuration or atomic rotation.
    pub fn register_trusted_signing_key(
        &self,
        att_type: AttestationType,
        key: VerifyingKey,
    ) {
        let old = self.roots.load();
        let mut new_bundle = (**old).clone();
        if !new_bundle
            .signing_keys
            .iter()
            .any(|(existing_type, existing_key)| *existing_type == att_type && existing_key == &key)
        {
            new_bundle.signing_keys.push((att_type, key));
            new_bundle.version += 1;
            self.roots.store(Arc::new(new_bundle));
        }
    }

    /// Verify attestation evidence.
    pub fn verify(
        &self,
        evidence: &AttestationEvidence,
        timestamp: f64,
    ) -> AttestationVerification {
        match evidence {
            AttestationEvidence::None => AttestationVerification {
                is_valid: true,
                attestation_type: AttestationType::None,
                measurement: vec![],
                timestamp,
                details: "No attestation required (software-only).".to_string(),
            },
            AttestationEvidence::Tpm(quote) => self.verify_tpm_quote(quote, timestamp),
            AttestationEvidence::Hsm(att) => self.verify_hsm_attestation(att, timestamp),
            AttestationEvidence::Tee(tee) => self.verify_tee_attestation(tee, timestamp),
        }
    }

    /// Verify a TPM 2.0 quote.
    fn verify_tpm_quote(&self, quote: &TpmQuote, timestamp: f64) -> AttestationVerification {
        // Verify quote structure
        if quote.quote_data.is_empty() || quote.pcr_values.is_empty() || quote.signature.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "Invalid TPM quote structure".to_string(),
            };
        }

        // #5 FIX: Verify freshness binding â€” nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session
        // and prevents replay of captured attestations.
        if quote.nonce.is_empty()
            || quote.channel_binding.is_empty()
            || quote.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "TPM quote missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age â€” rejects stale quotes beyond max_quote_age.
        // A quote_timestamp of 0.0 means the TPM did not embed a timestamp, in
        // which case the age check is skipped (backward compatibility with
        // stubs that do not produce real quotes).
        let age_valid = if quote.quote_timestamp > 0.0 {
            let age = timestamp - quote.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!("TPM quote timestamp is in the future (skew {}s)", -age),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TPM quote expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
            true
        } else {
            false
        };

        // Verify PCR values against trusted measurements (lock-free ArcSwap read).
        let roots = self.roots.load();
        let pcr_valid = roots
            .measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Tpm && m == &quote.pcr_values);

        // Verify signature over quote data INCLUDING the freshness binding.
        // The AIK public key (aik_public) must be the exact verifying key whose
        // corresponding private key signed the digest below. Any 64-byte blob,
        // replayed attestation, or wrong-key signature is rejected here.
        let sig_input = Self::compute_quote_digest(
            &quote.quote_data,
            &quote.pcr_values,
            &quote.nonce,
            &quote.channel_binding,
            &quote.suite_transcript_hash,
        );
        let sig_valid = Self::verify_ed25519_signature(
            &quote.aik_public,
            &sig_input,
            &quote.signature,
        );
        let key_trusted = roots.signing_keys.iter().any(|(t, key)| {
            *t == AttestationType::Tpm && key.as_bytes() == quote.aik_public.as_slice()
        });

        AttestationVerification {
            is_valid: pcr_valid && sig_valid && key_trusted,
            attestation_type: AttestationType::Tpm,
            measurement: quote.pcr_values.clone(),
            timestamp,
            details: format!(
                "TPM quote verification: PCR match={}, signature valid={}, trusted key={}, freshness bound={}, age_valid={}",
                pcr_valid, sig_valid, key_trusted, !quote.nonce.is_empty(), age_valid
            ),
        }
    }

    /// Verify an HSM attestation.
    ///
    /// Validates:
    /// 1. Structure completeness (key_attestation, manufacturer_cert, signing_public_key)
    /// 2. Freshness binding (nonce, channel_binding, suite_transcript_hash must be non-empty)
    /// 3. Quote age (rejected if beyond `max_quote_age`)
    /// 4. Ed25519 signature over [`AttestationVerifier::compute_hsm_attestation_digest`]
    fn verify_hsm_attestation(
        &self,
        att: &HsmAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Step 1: Structure completeness
        if att.key_attestation.is_empty()
            || att.manufacturer_cert.is_empty()
            || att.signing_public_key.is_empty()
            || att.signature.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Hsm,
                measurement: vec![],
                timestamp,
                details: "Invalid HSM attestation structure: missing required fields".to_string(),
            };
        }

        // Step 2: Freshness binding â€” nonce + channel_binding + suite_transcript_hash
        // must all be non-empty to bind this attestation to the current session.
        if att.nonce.is_empty()
            || att.channel_binding.is_empty()
            || att.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Hsm,
                measurement: vec![],
                timestamp,
                details: "HSM attestation missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // Step 3: Quote age check â€” same freshness window as TPM/TEE.
        if att.quote_timestamp > 0.0 {
            let age = timestamp - att.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Hsm,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "HSM attestation timestamp is in the future (skew {}s)",
                        -age
                    ),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Hsm,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "HSM attestation expired: age {age}s exceeds max_quote_age {}s",
                        self.max_quote_age
                    ),
                };
            }
        }

        // Load one immutable root snapshot for both signature and trust checks.
        // Keeping this load in the same verification scope prevents a live root
        // rotation from producing a mixed-version decision.
        let roots = self.roots.load();

        // Step 4: Ed25519 signature verification over the attestation digest.
        // The digest covers key_attestation + freshness fields, domain-separated.
        let digest = Self::compute_hsm_attestation_digest(
            &att.key_attestation,
            &att.nonce,
            &att.channel_binding,
            &att.suite_transcript_hash,
        );
        let sig_valid = Self::verify_ed25519_signature(
            &att.signing_public_key,
            &digest,
            &att.signature,
        );
        let key_trusted = VerifyingKey::from_bytes(match att.signing_public_key.as_slice().try_into() {
            Ok(bytes) => bytes,
            Err(_) => return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Hsm,
                measurement: vec![],
                timestamp,
                details: "HSM attestation signing key has invalid length".to_string(),
            },
        }).ok().is_some_and(|key| {
            roots.signing_keys.iter().any(|(t, trusted)| {
                *t == AttestationType::Hsm && trusted == &key
            })
        });

        AttestationVerification {
            is_valid: sig_valid && key_trusted,
            attestation_type: AttestationType::Hsm,
            measurement: att.key_attestation.clone(),
            timestamp,
            details: format!(
                "HSM attestation verification: token={}, sig_valid={sig_valid}, \
                 trusted_key={key_trusted}, freshness_bound=true, age_valid={}",
                att.token_label,
                att.quote_timestamp > 0.0
            ),
        }
    }

    /// Verify a TEE/Enclave attestation.
    fn verify_tee_attestation(
        &self,
        tee: &TeeAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Verify measurement against trusted values (lock-free ArcSwap read).
        let roots = self.roots.load();
        let measurement_valid = roots
            .measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Enclave && m == &tee.measurement);

        // #5 FIX: Verify freshness binding â€” nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session.
        if tee.nonce.is_empty()
            || tee.channel_binding.is_empty()
            || tee.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Enclave,
                measurement: vec![],
                timestamp,
                details: "TEE attestation missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age â€” rejects stale TEE reports beyond max_quote_age.
        // A quote_timestamp of 0.0 means no timestamp was provided; skip the check.
        if tee.quote_timestamp > 0.0 {
            let age = timestamp - tee.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation timestamp is in the future (skew {}s)",
                        -age
                    ),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
        }

        // Verify signature over the TEE report digest INCLUDING freshness binding.
        // The signing_public_key (TEE manufacturer / quoting enclave key) must be the
        // exact verifying key. Any empty blob, random bytes, or wrong-key signature
        // is rejected cryptographically â€” not merely by a length or emptiness check.
        let tee_digest = Self::compute_tee_report_digest(
            &tee.measurement,
            &tee.report_data,
            &tee.nonce,
            &tee.channel_binding,
            &tee.suite_transcript_hash,
        );
        let sig_valid = Self::verify_ed25519_signature(
            &tee.signing_public_key,
            &tee_digest,
            &tee.signature,
        );
        let key_trusted = VerifyingKey::from_bytes(match tee.signing_public_key.as_slice().try_into() {
            Ok(bytes) => bytes,
            Err(_) => return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Enclave,
                measurement: vec![],
                timestamp,
                details: "TEE attestation signing key has invalid length".to_string(),
            },
        }).ok().is_some_and(|key| {
            roots.signing_keys.iter().any(|(t, trusted)| {
                *t == AttestationType::Enclave && trusted == &key
            })
        });

        AttestationVerification {
            is_valid: measurement_valid && sig_valid && key_trusted,
            attestation_type: AttestationType::Enclave,
            measurement: tee.measurement.clone(),
            timestamp,
            details: format!(
                "TEE attestation verification: type={}, measurement valid={}, signature valid={}, \
                 trusted key={}, freshness bound={}, key present={}",
                tee.tee_type,
                measurement_valid,
                sig_valid,
                key_trusted,
                !tee.nonce.is_empty(),
                !tee.signing_public_key.is_empty(),
            ),
        }
    }

    /// Compute the digest of a TPM quote for signature verification.
    ///
    /// Includes freshness binding (nonce, channel_binding, suite_transcript_hash)
    /// so the signature covers the full session context and cannot be replayed.
    ///
    /// `pub(crate)` so that test helpers can produce correctly-signed test quotes
    /// without exposing the function as public API.
    pub(crate) fn compute_quote_digest(
        quote_data: &[u8],
        pcr_values: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-TPM-quote-digest-v2");
        // Freshness binding â€” length-prefixed to prevent extension attacks
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        // Quote payload
        hasher.update((quote_data.len() as u32).to_be_bytes());
        hasher.update(quote_data);
        hasher.update((pcr_values.len() as u32).to_be_bytes());
        hasher.update(pcr_values);
        hasher.finalize().to_vec()
    }

    /// Compute the digest of a TEE report for signature verification.
    ///
    /// Includes freshness binding (nonce, channel_binding, suite_transcript_hash)
    /// so the signature covers the full session context and cannot be replayed.
    ///
    /// `pub(crate)` so that test helpers can produce correctly-signed reports.
    pub(crate) fn compute_tee_report_digest(
        measurement: &[u8],
        report_data: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-TEE-report-digest-v1");
        // Freshness binding â€” length-prefixed to prevent extension attacks
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        // Report payload
        hasher.update((measurement.len() as u32).to_be_bytes());
        hasher.update(measurement);
        hasher.update((report_data.len() as u32).to_be_bytes());
        hasher.update(report_data);
        hasher.finalize().to_vec()
    }

    /// Compute the digest of an HSM attestation for signature verification.
    ///
    /// Domain-separated from TPM and TEE digests. Uses the same length-prefixed
    /// SHA-256 pattern as [`Self::compute_quote_digest`] and
    /// [`Self::compute_tee_report_digest`] to prevent extension attacks.
    ///
    /// Covers `key_attestation` + freshness fields (nonce, channel_binding,
    /// suite_transcript_hash). The PKCS#11 token_label and manufacturer_cert
    /// are NOT included in the digest because they are advisory metadata;
    /// the signing key is the trust anchor, not the label.
    ///
    /// `pub(crate)` so that test helpers can produce correctly-signed attestations.
    pub(crate) fn compute_hsm_attestation_digest(
        key_attestation: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-HSM-attestation-digest-v1");
        // Freshness binding â€” length-prefixed to prevent extension attacks
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        // Key attestation payload
        hasher.update((key_attestation.len() as u32).to_be_bytes());
        hasher.update(key_attestation);
        hasher.finalize().to_vec()
    }

    /// Verify an Ed25519 signature over a message using a raw 32-byte public key.
    ///
    /// Returns `false` â€” never panics â€” on any of:
    /// - `public_key_bytes` is not exactly 32 bytes
    /// - `signature_bytes` is not exactly 64 bytes
    /// - the key bytes do not represent a valid compressed Ed25519 point
    /// - the signature does not verify against the key and message
    ///
    /// `pub(crate)` so the test submodule can exercise it directly as a unit test.
    /// Not exposed as public API â€” callers should use `AttestationVerifier::verify`.
    pub(crate) fn verify_ed25519_signature(
        public_key_bytes: &[u8],
        message: &[u8],
        signature_bytes: &[u8],
    ) -> bool {
        // Parse public key â€” must be exactly 32 bytes
        let pk_array: [u8; 32] = match public_key_bytes.try_into() {
            Ok(a) => a,
            Err(_) => return false,
        };
        let verifying_key = match VerifyingKey::from_bytes(&pk_array) {
            Ok(vk) => vk,
            Err(_) => return false,
        };
        // Parse signature â€” must be exactly 64 bytes
        let sig_array: [u8; 64] = match signature_bytes.try_into() {
            Ok(a) => a,
            Err(_) => return false,
        };
        let signature = Signature::from_bytes(&sig_array);
        // Cryptographic verification â€” the only accepted path to `true`
        verifying_key.verify(message, &signature).is_ok()
    }
}

impl Default for AttestationVerifier {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate an attestation challenge for a peer.
/// The challenge is a nonce that the peer must include in its attestation.
pub fn generate_attestation_challenge() -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    challenge
}

/// Verify an attestation challenge response.
pub fn verify_challenge_response(
    challenge: &[u8],
    response: &[u8],
    expected_binding: &[u8],
) -> bool {
    // Response should be HMAC(challenge, binding)
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let mut mac = match HmacSha256::new_from_slice(expected_binding) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(challenge);
    let expected = mac.finalize().into_bytes();
    crate::security::constant_time_eq(response, &expected)
}

/// Create an attestation binding that ties a keypair to hardware.
/// #5 FIX: Includes nonce and channel_binding to bind the attestation to a specific session.
pub fn create_attestation_binding(
    public_key: &[u8],
    measurement: &[u8],
    attestation_type: AttestationType,
    nonce: &[u8],
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    let mut hasher = Sha256::new();
    hasher.update(domain_separation::ATTESTATION_CHALLENGE);
    // #5 FIX: Include freshness binding in the attestation binding
    hasher.update((nonce.len() as u32).to_be_bytes());
    hasher.update(nonce);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.update(public_key);
    hasher.update(measurement);
    hasher.update(attestation_type.as_str().as_bytes());
    hasher.finalize().to_vec()
}

/// #5 FIX: Create a fresh attestation challenge that includes the channel binding
/// and suite transcript hash. This ensures the attestation is bound to this specific
/// session and cannot be replayed.
pub fn create_fresh_attestation_challenge(
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    // Bind the challenge to the session context
    let mut hasher = Sha256::new();
    hasher.update(b"SAACP-attestation-challenge-v2");
    hasher.update(&challenge);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.finalize().to_vec()
}

/// Maximum attestation quote size (bytes).
pub const MAX_ATTESTATION_QUOTE_SIZE: usize = max_sizes::MAX_ATTESTATION_QUOTE;

/// Validate attestation quote size to prevent DoS.
pub fn validate_attestation_size(quote_size: usize) -> Result<(), PqcError> {
    if quote_size > MAX_ATTESTATION_QUOTE_SIZE {
        return Err(PqcError::InvalidLength(format!(
            "Attestation quote exceeds maximum size: {} > {}",
            quote_size, MAX_ATTESTATION_QUOTE_SIZE
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::Signer;

    // â”€â”€ Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// Generate a random Ed25519 signing keypair for tests.
    fn test_keypair() -> ed25519_dalek::SigningKey {
        ed25519_dalek::SigningKey::generate(&mut rand::rngs::OsRng)
    }

    /// Build a fully-valid `TpmQuote` whose signature was produced by `signing_key`.
    fn make_valid_tpm_quote(signing_key: &ed25519_dalek::SigningKey) -> TpmQuote {
        let quote_data = vec![1u8; 100];
        let pcr_values = vec![1u8; 32];
        let nonce = vec![0xAAu8; 32];
        let channel_binding = vec![0xBBu8; 32];
        let suite_transcript_hash = vec![0xCCu8; 32];

        let digest = AttestationVerifier::compute_quote_digest(
            &quote_data,
            &pcr_values,
            &nonce,
            &channel_binding,
            &suite_transcript_hash,
        );
        let signature: ed25519_dalek::Signature = signing_key.sign(&digest);

        TpmQuote {
            quote_data,
            pcr_values,
            signature: signature.to_bytes().to_vec(),
            aik_public: signing_key.verifying_key().to_bytes().to_vec(),
            nonce,
            channel_binding,
            suite_transcript_hash,
            quote_timestamp: 0.0,
        }
    }

    /// Build a fully-valid `TeeAttestation` whose signature was produced by `signing_key`.
    fn make_valid_tee_attest(signing_key: &ed25519_dalek::SigningKey) -> TeeAttestation {
        let measurement = vec![0xDDu8; 32];
        let report_data = vec![0xEEu8; 64];
        let nonce = vec![0x11u8; 32];
        let channel_binding = vec![0x22u8; 32];
        let suite_transcript_hash = vec![0x33u8; 32];

        let digest = AttestationVerifier::compute_tee_report_digest(
            &measurement,
            &report_data,
            &nonce,
            &channel_binding,
            &suite_transcript_hash,
        );
        let signature: ed25519_dalek::Signature = signing_key.sign(&digest);

        TeeAttestation {
            measurement,
            report_data,
            signature: signature.to_bytes().to_vec(),
            tee_type: "sgx".to_string(),
            signing_public_key: signing_key.verifying_key().to_bytes().to_vec(),
            nonce,
            channel_binding,
            suite_transcript_hash,
            quote_timestamp: 0.0,
        }
    }

    // â”€â”€ Unchanged basic tests â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    #[test]
    fn test_attestation_type_strings() {
        assert_eq!(AttestationType::None.as_str(), "none");
        assert_eq!(AttestationType::from_str("tpm"), Some(AttestationType::Tpm));
        assert!(AttestationType::Tpm.requires_hardware());
        assert!(!AttestationType::None.requires_hardware());
    }

    #[test]
    fn test_attestation_type_is_implemented() {
        assert!(AttestationType::None.is_implemented());
        assert!(AttestationType::Tpm.is_implemented());
        assert!(AttestationType::Hsm.is_implemented());
        assert!(AttestationType::Tee.is_implemented());
        assert!(AttestationType::Enclave.is_implemented());
    }

    #[test]
    fn test_attestation_verifier_none() {
        let verifier = AttestationVerifier::new();
        let result = verifier.verify(&AttestationEvidence::None, 0.0);
        assert!(result.is_valid);
    }

    #[test]
    fn test_attestation_challenge() {
        let challenge = generate_attestation_challenge();
        assert_eq!(challenge.len(), 32);
    }

    #[test]
    fn test_attestation_binding() {
        let nonce = vec![1u8; 32];
        let channel_binding = vec![2u8; 32];
        let suite_transcript_hash = vec![3u8; 32];
        let binding = create_attestation_binding(
            b"pubkey",
            b"measurement",
            AttestationType::Tpm,
            &nonce,
            &channel_binding,
            &suite_transcript_hash,
        );
        assert_eq!(binding.len(), 32);
    }

    #[test]
    fn test_validate_attestation_size() {
        assert!(validate_attestation_size(1000).is_ok());
        assert!(validate_attestation_size(max_sizes::MAX_ATTESTATION_QUOTE + 1).is_err());
    }

    // â”€â”€ TPM: valid path â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// A correctly-signed quote with a matching AIK public key must be accepted.
    #[test]
    fn test_tpm_quote_verification() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        verifier.register_trusted_signing_key(AttestationType::Tpm, sk.verifying_key());

        let quote = make_valid_tpm_quote(&sk);
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(result.is_valid, "Valid TPM quote with correct signature must be accepted");
    }

    // â”€â”€ TPM: freshness binding â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// A quote missing nonce/channel/transcript must be rejected before signature check.
    #[test]
    fn test_tpm_quote_without_freshness_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let mut quote = make_valid_tpm_quote(&sk);
        quote.nonce = vec![];
        quote.channel_binding = vec![];
        quote.suite_transcript_hash = vec![];

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "TPM quote without freshness binding should be rejected"
        );
    }

    // â”€â”€ TPM: adversarial signature tests â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// A random 64-byte blob submitted as a TPM signature must be rejected
    /// (previously the placeholder `len >= 64` would have accepted this).
    #[test]
    fn test_tpm_forged_signature_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let mut quote = make_valid_tpm_quote(&sk);
        // Overwrite the valid signature with 64 bytes of garbage
        quote.signature = vec![0xFFu8; 64];

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "Forged 64-byte TPM signature must be rejected by real verification"
        );
    }

    /// A valid Ed25519 signature from a *different* key must be rejected.
    #[test]
    fn test_tpm_wrong_aik_key_rejected() {
        let sk_signer = test_keypair();
        let sk_other = test_keypair();

        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let mut quote = make_valid_tpm_quote(&sk_signer);
        // Replace AIK with the *other* key's public bytes â€” signature no longer matches
        quote.aik_public = sk_other.verifying_key().to_bytes().to_vec();

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "TPM quote signed by one key must be rejected when verified against a different key"
        );
    }

    /// An AIK public key with the wrong byte length (not 32) must be rejected.
    #[test]
    fn test_tpm_malformed_aik_key_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let mut quote = make_valid_tpm_quote(&sk);
        // 31 bytes â€” not a valid Ed25519 compressed point
        quote.aik_public = vec![0u8; 31];

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "Malformed AIK key (wrong length) must be rejected"
        );
    }

    /// An empty AIK public key must be rejected.
    #[test]
    fn test_tpm_empty_aik_key_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let mut quote = make_valid_tpm_quote(&sk);
        quote.aik_public = vec![];

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "Empty AIK key must be rejected"
        );
    }

    // â”€â”€ TEE: valid path â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// A correctly-signed TEE report with a matching signing public key must be accepted.
    #[test]
    fn test_tee_valid_signature_accepted() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![0xDDu8; 32]);
        verifier.register_trusted_signing_key(AttestationType::Enclave, sk.verifying_key());

        let tee = make_valid_tee_attest(&sk);
        let result = verifier.verify(&AttestationEvidence::Tee(tee), 0.0);
        assert!(result.is_valid, "Valid TEE attestation with correct signature must be accepted");
    }

    // â”€â”€ TEE: adversarial signature tests â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// A non-empty but random blob submitted as a TEE signature must be rejected
    /// (previously the placeholder `!is_empty()` would have accepted this).
    #[test]
    fn test_tee_forged_signature_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![0xDDu8; 32]);

        let mut tee = make_valid_tee_attest(&sk);
        // Overwrite the valid signature with 64 bytes of garbage
        tee.signature = vec![0xFFu8; 64];

        let result = verifier.verify(&AttestationEvidence::Tee(tee), 0.0);
        assert!(
            !result.is_valid,
            "Forged 64-byte TEE signature must be rejected by real verification"
        );
    }

    /// A valid Ed25519 signature from a *different* key must be rejected for TEE.
    #[test]
    fn test_tee_wrong_key_rejected() {
        let sk_signer = test_keypair();
        let sk_other = test_keypair();

        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![0xDDu8; 32]);

        let mut tee = make_valid_tee_attest(&sk_signer);
        // Replace signing_public_key with a different key's bytes
        tee.signing_public_key = sk_other.verifying_key().to_bytes().to_vec();

        let result = verifier.verify(&AttestationEvidence::Tee(tee), 0.0);
        assert!(
            !result.is_valid,
            "TEE attestation signed by one key must be rejected when verified against a different key"
        );
    }

    /// A TEE report with missing freshness binding must be rejected before signature check.
    #[test]
    fn test_tee_without_freshness_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![0xDDu8; 32]);

        let mut tee = make_valid_tee_attest(&sk);
        tee.nonce = vec![];
        tee.channel_binding = vec![];
        tee.suite_transcript_hash = vec![];

        let result = verifier.verify(&AttestationEvidence::Tee(tee), 0.0);
        assert!(
            !result.is_valid,
            "TEE attestation without freshness binding must be rejected"
        );
    }

    /// An empty TEE signing public key must be rejected.
    #[test]
    fn test_tee_empty_signing_key_rejected() {
        let sk = test_keypair();
        let verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![0xDDu8; 32]);

        let mut tee = make_valid_tee_attest(&sk);
        tee.signing_public_key = vec![];

        let result = verifier.verify(&AttestationEvidence::Tee(tee), 0.0);
        assert!(
            !result.is_valid,
            "Empty TEE signing key must be rejected"
        );
    }

    // â”€â”€ verify_ed25519_signature unit tests â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// The low-level helper correctly verifies a genuine signature.
    #[test]
    fn test_verify_ed25519_signature_valid() {
        let sk = test_keypair();
        let msg = b"test message for attestation";
        let sig: ed25519_dalek::Signature = sk.sign(msg);

        assert!(
            AttestationVerifier::verify_ed25519_signature(
                &sk.verifying_key().to_bytes(),
                msg,
                &sig.to_bytes(),
            ),
            "Genuine Ed25519 signature must verify"
        );
    }

    /// The low-level helper rejects a signature over a different message.
    #[test]
    fn test_verify_ed25519_signature_wrong_message_rejected() {
        let sk = test_keypair();
        let sig: ed25519_dalek::Signature = sk.sign(b"original message");

        assert!(
            !AttestationVerifier::verify_ed25519_signature(
                &sk.verifying_key().to_bytes(),
                b"tampered message",
                &sig.to_bytes(),
            ),
            "Signature over a different message must not verify"
        );
    }
}
