//! Hardware Attestation Module
//!
//! Implements TPM/HSM/TEE attestation verification for SAACP.
//! Provides cryptographic proof that a peer is running approved code
//! on trusted hardware before session establishment.
//!
//! # Attestation Types
//! - **TPM 2.0**: TPM quote verification via PCR values
//! - **HSM**: PKCS#11-based key attestation
//! - **TEE/Enclave**: Intel SGX / ARM TrustZone attestation
//!
//! # Security Properties
//! - Prevents session establishment with untrusted hardware
//! - Binds cryptographic identity to hardware root of trust
//! - Enables compliance with healthcare/banking hardware requirements

use sha2::{Digest, Sha256};

use crate::pqc::domain_separation;
use crate::pqc::max_sizes;
use crate::pqc::PqcError;

/// Attestation verification result.
#[derive(Debug, Clone)]
pub struct AttestationVerification {
    /// Whether the attestation is valid.
    pub is_valid: bool,
    /// The attestation type verified.
    pub attestation_type: AttestationType,
    /// Measurement (PCR values / enclave hash) that was verified.
    pub measurement: Vec<u8>,
    /// Timestamp of the attestation.
    pub timestamp: f64,
    /// Human-readable verification details.
    pub details: String,
}

/// Attestation types supported by SAACP.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttestationType {
    /// No attestation (software-only, no hardware root of trust).
    None,
    /// TPM 2.0 quote attestation.
    Tpm,
    /// HSM key attestation via PKCS#11.
    Hsm,
    /// Trusted Execution Environment (TEE).
    Tee,
    /// Secure Enclave (Intel SGX, ARM TrustZone, Apple Secure Enclave).
    Enclave,
}

impl AttestationType {
    /// String representation.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Tpm => "tpm",
            Self::Hsm => "hsm",
            Self::Tee => "tee",
            Self::Enclave => "enclave",
        }
    }

    /// Parse from string.
    ///
    /// Deliberately an inherent method (Python-parity shape), not a `FromStr`
    /// impl — see `cluster.rs`'s matching `#[allow]` for the rationale.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "none" => Some(Self::None),
            "tpm" => Some(Self::Tpm),
            "hsm" => Some(Self::Hsm),
            "tee" => Some(Self::Tee),
            "enclave" => Some(Self::Enclave),
            _ => None,
        }
    }

    /// Whether this attestation type requires hardware.
    pub fn requires_hardware(&self) -> bool {
        !matches!(self, Self::None)
    }

    /// Whether this attestation type has a production implementation.
    pub fn is_implemented(&self) -> bool {
        matches!(self, Self::None | Self::Tpm | Self::Hsm)
    }
}

/// TPM 2.0 attestation quote.
#[derive(Debug, Clone)]
pub struct TpmQuote {
    /// TPM quote structure (PCR values, signature).
    pub quote_data: Vec<u8>,
    /// Platform Configuration Register values.
    pub pcr_values: Vec<u8>,
    /// TPM signature over the quote.
    pub signature: Vec<u8>,
    /// AIK (Attestation Identity Key) public key.
    pub aik_public: Vec<u8>,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the quote was generated by the TPM.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// HSM attestation via PKCS#11.
#[derive(Debug, Clone)]
pub struct HsmAttestation {
    /// PKCS#11 token label.
    pub token_label: String,
    /// Key handle attestation.
    pub key_attestation: Vec<u8>,
    /// HSM manufacturer certificate.
    pub manufacturer_cert: Vec<u8>,
}

/// TEE/Enclave attestation report.
#[derive(Debug, Clone)]
pub struct TeeAttestation {
    /// Enclave measurement (MRENCLAVE / MRMEASUREMENT).
    pub measurement: Vec<u8>,
    /// Attestation report data.
    pub report_data: Vec<u8>,
    /// Signature over the report.
    pub signature: Vec<u8>,
    /// TEE type identifier.
    pub tee_type: String,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the attestation was generated.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// Attestation evidence that can be verified.
#[derive(Debug, Clone)]
pub enum AttestationEvidence {
    /// No evidence (software-only).
    None,
    /// TPM quote evidence.
    Tpm(TpmQuote),
    /// HSM attestation evidence.
    Hsm(HsmAttestation),
    /// TEE/Enclave attestation evidence.
    Tee(TeeAttestation),
}

/// Attestation verifier for hardware root of trust.
pub struct AttestationVerifier {
    /// Trusted measurements (PCR values, enclave hashes) indexed by type.
    trusted_measurements: Vec<(AttestationType, Vec<u8>)>,
    /// Maximum age of an attestation quote (seconds).
    max_quote_age: f64,
}

impl AttestationVerifier {
    /// Create a new attestation verifier with default settings.
    pub fn new() -> Self {
        Self {
            trusted_measurements: Vec::new(),
            max_quote_age: 300.0, // 5 minutes
        }
    }

    /// Create with custom max quote age.
    pub fn with_max_quote_age(max_age: f64) -> Self {
        Self {
            trusted_measurements: Vec::new(),
            max_quote_age: max_age,
        }
    }

    /// Register a trusted measurement for verification.
    pub fn register_trusted_measurement(
        &mut self,
        att_type: AttestationType,
        measurement: Vec<u8>,
    ) {
        self.trusted_measurements.push((att_type, measurement));
    }

    /// Verify attestation evidence.
    pub fn verify(
        &self,
        evidence: &AttestationEvidence,
        timestamp: f64,
    ) -> AttestationVerification {
        match evidence {
            AttestationEvidence::None => AttestationVerification {
                is_valid: true,
                attestation_type: AttestationType::None,
                measurement: vec![],
                timestamp,
                details: "No attestation required (software-only).".to_string(),
            },
            AttestationEvidence::Tpm(quote) => self.verify_tpm_quote(quote, timestamp),
            AttestationEvidence::Hsm(att) => self.verify_hsm_attestation(att, timestamp),
            AttestationEvidence::Tee(tee) => self.verify_tee_attestation(tee, timestamp),
        }
    }

    /// Verify a TPM 2.0 quote.
    fn verify_tpm_quote(&self, quote: &TpmQuote, timestamp: f64) -> AttestationVerification {
        // Verify quote structure
        if quote.quote_data.is_empty() || quote.pcr_values.is_empty() || quote.signature.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "Invalid TPM quote structure".to_string(),
            };
        }

        // #5 FIX: Verify freshness binding — nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session
        // and prevents replay of captured attestations.
        if quote.nonce.is_empty()
            || quote.channel_binding.is_empty()
            || quote.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "TPM quote missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age — rejects stale quotes beyond max_quote_age.
        // A quote_timestamp of 0.0 means the TPM did not embed a timestamp, in
        // which case the age check is skipped (backward compatibility with
        // stubs that do not produce real quotes).
        let age_valid = if quote.quote_timestamp > 0.0 {
            let age = timestamp - quote.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!("TPM quote timestamp is in the future (skew {}s)", -age),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TPM quote expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
            true
        } else {
            false
        };

        // Verify PCR values against trusted measurements
        let pcr_valid = self
            .trusted_measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Tpm && m == &quote.pcr_values);

        // #5 FIX: Verify signature over quote data INCLUDING the freshness binding.
        // The signature must cover nonce || channel_binding || suite_transcript_hash || quote_data || pcr_values.
        let _sig_input = Self::compute_quote_digest(
            &quote.quote_data,
            &quote.pcr_values,
            &quote.nonce,
            &quote.channel_binding,
            &quote.suite_transcript_hash,
        );
        let sig_valid = quote.signature.len() >= 64; // Placeholder: verify against AIK public key

        AttestationVerification {
            is_valid: pcr_valid && sig_valid,
            attestation_type: AttestationType::Tpm,
            measurement: quote.pcr_values.clone(),
            timestamp,
            details: format!(
                "TPM quote verification: PCR match={}, signature valid={}, freshness bound={}, age_valid={}",
                pcr_valid, sig_valid, !quote.nonce.is_empty(), age_valid
            ),
        }
    }

    /// Verify an HSM attestation.
    fn verify_hsm_attestation(
        &self,
        att: &HsmAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Verify key attestation structure
        if att.key_attestation.is_empty() {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Hsm,
                measurement: vec![],
                timestamp,
                details: "Invalid HSM attestation structure".to_string(),
            };
        }

        // Verify manufacturer certificate chain (simplified)
        let cert_valid = !att.manufacturer_cert.is_empty();

        AttestationVerification {
            is_valid: cert_valid,
            attestation_type: AttestationType::Hsm,
            measurement: att.key_attestation.clone(),
            timestamp,
            details: format!(
                "HSM attestation verification: token={}, cert valid={}",
                att.token_label, cert_valid
            ),
        }
    }

    /// Verify a TEE/Enclave attestation.
    fn verify_tee_attestation(
        &self,
        tee: &TeeAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Verify measurement against trusted values
        let measurement_valid = self
            .trusted_measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Enclave && m == &tee.measurement);

        // #5 FIX: Verify freshness binding — nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session.
        if tee.nonce.is_empty()
            || tee.channel_binding.is_empty()
            || tee.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Enclave,
                measurement: vec![],
                timestamp,
                details: "TEE attestation missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age — rejects stale TEE reports beyond max_quote_age.
        // A quote_timestamp of 0.0 means no timestamp was provided; skip the check.
        if tee.quote_timestamp > 0.0 {
            let age = timestamp - tee.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation timestamp is in the future (skew {}s)",
                        -age
                    ),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
        }

        // Verify signature over report data
        let sig_valid = !tee.signature.is_empty();

        AttestationVerification {
            is_valid: measurement_valid && sig_valid,
            attestation_type: AttestationType::Enclave,
            measurement: tee.measurement.clone(),
            timestamp,
            details: format!(
                "TEE attestation verification: measurement valid={}, signature valid={}, freshness bound={}",
                measurement_valid, sig_valid, !tee.nonce.is_empty()
            ),
        }
    }

    /// Compute the digest of a TPM quote for signature verification.
    /// #5 FIX: Includes freshness binding (nonce, channel_binding, suite_transcript_hash)
    /// in the digest so the signature covers the full session context.
    fn compute_quote_digest(
        quote_data: &[u8],
        pcr_values: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-TPM-quote-digest-v2");
        // #5 FIX: Include freshness binding in the digest
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        hasher.update((quote_data.len() as u32).to_be_bytes());
        hasher.update(quote_data);
        hasher.update((pcr_values.len() as u32).to_be_bytes());
        hasher.update(pcr_values);
        hasher.finalize().to_vec()
    }
}

impl Default for AttestationVerifier {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate an attestation challenge for a peer.
/// The challenge is a nonce that the peer must include in its attestation.
pub fn generate_attestation_challenge() -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    challenge
}

/// Verify an attestation challenge response.
pub fn verify_challenge_response(
    challenge: &[u8],
    response: &[u8],
    expected_binding: &[u8],
) -> bool {
    // Response should be HMAC(challenge, binding)
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let mut mac = match HmacSha256::new_from_slice(expected_binding) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(challenge);
    let expected = mac.finalize().into_bytes();
    crate::security::constant_time_eq(response, &expected)
}

/// Create an attestation binding that ties a keypair to hardware.
/// #5 FIX: Includes nonce and channel_binding to bind the attestation to a specific session.
pub fn create_attestation_binding(
    public_key: &[u8],
    measurement: &[u8],
    attestation_type: AttestationType,
    nonce: &[u8],
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    let mut hasher = Sha256::new();
    hasher.update(domain_separation::ATTESTATION_CHALLENGE);
    // #5 FIX: Include freshness binding in the attestation binding
    hasher.update((nonce.len() as u32).to_be_bytes());
    hasher.update(nonce);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.update(public_key);
    hasher.update(measurement);
    hasher.update(attestation_type.as_str().as_bytes());
    hasher.finalize().to_vec()
}

/// #5 FIX: Create a fresh attestation challenge that includes the channel binding
/// and suite transcript hash. This ensures the attestation is bound to this specific
/// session and cannot be replayed.
pub fn create_fresh_attestation_challenge(
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    // Bind the challenge to the session context
    let mut hasher = Sha256::new();
    hasher.update(b"SAACP-attestation-challenge-v2");
    hasher.update(&challenge);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.finalize().to_vec()
}

/// Maximum attestation quote size (bytes).
pub const MAX_ATTESTATION_QUOTE_SIZE: usize = max_sizes::MAX_ATTESTATION_QUOTE;

/// Validate attestation quote size to prevent DoS.
pub fn validate_attestation_size(quote_size: usize) -> Result<(), PqcError> {
    if quote_size > MAX_ATTESTATION_QUOTE_SIZE {
        return Err(PqcError::InvalidLength(format!(
            "Attestation quote exceeds maximum size: {} > {}",
            quote_size, MAX_ATTESTATION_QUOTE_SIZE
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_attestation_type_strings() {
        assert_eq!(AttestationType::None.as_str(), "none");
        assert_eq!(AttestationType::from_str("tpm"), Some(AttestationType::Tpm));
        assert!(AttestationType::Tpm.requires_hardware());
        assert!(!AttestationType::None.requires_hardware());
    }

    #[test]
    fn test_attestation_verifier_none() {
        let verifier = AttestationVerifier::new();
        let result = verifier.verify(&AttestationEvidence::None, 0.0);
        assert!(result.is_valid);
    }

    #[test]
    fn test_attestation_challenge() {
        let challenge = generate_attestation_challenge();
        assert_eq!(challenge.len(), 32);
    }

    #[test]
    fn test_attestation_binding() {
        let nonce = vec![1u8; 32];
        let channel_binding = vec![2u8; 32];
        let suite_transcript_hash = vec![3u8; 32];
        let binding = create_attestation_binding(
            b"pubkey",
            b"measurement",
            AttestationType::Tpm,
            &nonce,
            &channel_binding,
            &suite_transcript_hash,
        );
        assert_eq!(binding.len(), 32);
    }

    #[test]
    fn test_validate_attestation_size() {
        assert!(validate_attestation_size(1000).is_ok());
        assert!(validate_attestation_size(max_sizes::MAX_ATTESTATION_QUOTE + 1).is_err());
    }

    #[test]
    fn test_tpm_quote_verification() {
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let quote = TpmQuote {
            quote_data: vec![1u8; 100],
            pcr_values: vec![1u8; 32],
            signature: vec![0u8; 64],
            aik_public: vec![0u8; 32],
            // #5 FIX: Freshness binding fields
            nonce: vec![1u8; 32],
            channel_binding: vec![2u8; 32],
            suite_transcript_hash: vec![3u8; 32],
            // No timestamp — age check is skipped (backward compat with stubs).
            quote_timestamp: 0.0,
        };

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(result.is_valid);
    }

    /// #5 FIX: Test that attestation without freshness binding is rejected.
    #[test]
    fn test_tpm_quote_without_freshness_rejected() {
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);

        let quote = TpmQuote {
            quote_data: vec![1u8; 100],
            pcr_values: vec![1u8; 32],
            signature: vec![0u8; 64],
            aik_public: vec![0u8; 32],
            // Missing freshness binding
            nonce: vec![],
            channel_binding: vec![],
            suite_transcript_hash: vec![],
            quote_timestamp: 0.0,
        };

        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(
            !result.is_valid,
            "TPM quote without freshness binding should be rejected"
        );
    }
}
