//! Hardware Attestation Module
//!
//! Implements TPM/HSM/TEE attestation verification for SAACP.
//! Provides cryptographic proof that a peer is running approved code
//! on trusted hardware before session establishment.
//!
//! # Attestation Types
//! - **TPM 2.0**: TPM quote verification via PCR values
//! - **HSM**: PKCS#11-based key attestation
//! - **TEE/Enclave**: Intel SGX / ARM TrustZone attestation
//!
//! # Security Properties
//! - Prevents session establishment with untrusted hardware
//! - Binds cryptographic identity to hardware root of trust
//! - Enables compliance with healthcare/banking hardware requirements

use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};

use crate::pqc::domain_separation;
use crate::pqc::max_sizes;
use crate::pqc::PqcError;

/// Attestation verification result.
#[derive(Debug, Clone)]
pub struct AttestationVerification {
    /// Whether the attestation is valid.
    pub is_valid: bool,
    /// The attestation type verified.
    pub attestation_type: AttestationType,
    /// Measurement (PCR values / enclave hash) that was verified.
    pub measurement: Vec<u8>,
    /// Timestamp of the attestation.
    pub timestamp: f64,
    /// Human-readable verification details.
    pub details: String,
}

/// Attestation types supported by SAACP.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttestationType {
    /// No attestation (software-only, no hardware root of trust).
    None,
    /// TPM 2.0 quote attestation.
    Tpm,
    /// HSM key attestation via PKCS#11.
    Hsm,
    /// Trusted Execution Environment (TEE).
    Tee,
    /// Secure Enclave (Intel SGX, ARM TrustZone, Apple Secure Enclave).
    Enclave,
}

impl AttestationType {
    /// String representation.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Tpm => "tpm",
            Self::Hsm => "hsm",
            Self::Tee => "tee",
            Self::Enclave => "enclave",
        }
    }

    /// Parse from string.
    ///
    /// Deliberately an inherent method (Python-parity shape), not a `FromStr`
    /// impl — see `cluster.rs`'s matching `#[allow]` for the rationale.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "none" => Some(Self::None),
            "tpm" => Some(Self::Tpm),
            "hsm" => Some(Self::Hsm),
            "tee" => Some(Self::Tee),
            "enclave" => Some(Self::Enclave),
            _ => None,
        }
    }

    /// Whether this attestation type requires hardware.
    pub fn requires_hardware(&self) -> bool {
        !matches!(self, Self::None)
    }

    /// Whether this attestation type has a production implementation.
    pub fn is_implemented(&self) -> bool {
        matches!(self, Self::None | Self::Tpm | Self::Hsm)
    }
}

/// TPM 2.0 attestation quote.
#[derive(Debug, Clone)]
pub struct TpmQuote {
    /// TPM quote structure (PCR values, signature).
    pub quote_data: Vec<u8>,
    /// Platform Configuration Register values.
    pub pcr_values: Vec<u8>,
    /// TPM signature over the quote.
    pub signature: Vec<u8>,
    /// AIK (Attestation Identity Key) public key.
    pub aik_public: Vec<u8>,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the quote was generated by the TPM.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// HSM attestation via PKCS#11.
#[derive(Debug, Clone)]
pub struct HsmAttestation {
    /// PKCS#11 token label.
    pub token_label: String,
    /// Key handle attestation.
    pub key_attestation: Vec<u8>,
    /// HSM manufacturer certificate.
    pub manufacturer_cert: Vec<u8>,
}

/// TEE/Enclave attestation report.
#[derive(Debug, Clone)]
pub struct TeeAttestation {
    /// Enclave measurement (MRENCLAVE / MRMEASUREMENT).
    pub measurement: Vec<u8>,
    /// Attestation report data.
    pub report_data: Vec<u8>,
    /// #5 FIX: Signature over the TEE report digest.
    pub signature: Vec<u8>,
    /// TEE type identifier.
    pub tee_type: String,
    /// Public key used to verify `signature`.
    ///
    /// For Intel SGX ECDSA: the quoting enclave’s Ed25519 attestation key.
    /// For ARM TrustZone: the TEE manufacturer’s Ed25519 signing key.
    /// Must be exactly 32 bytes (raw Ed25519 compressed point).
    pub signing_public_key: Vec<u8>,
    /// #5 FIX: Nonce from the attestation challenge (binds quote to this session).
    pub nonce: Vec<u8>,
    /// #5 FIX: Channel binding value (binds quote to this specific channel).
    pub channel_binding: Vec<u8>,
    /// #5 FIX: Suite transcript hash (binds quote to this negotiation).
    pub suite_transcript_hash: Vec<u8>,
    /// #5 FIX: Unix timestamp (seconds) when the attestation was generated.
    /// Used for freshness checking against `AttestationVerifier::max_quote_age`.
    /// A value of 0.0 means "no timestamp provided" and skips the age check.
    pub quote_timestamp: f64,
}

/// Attestation evidence that can be verified.
#[derive(Debug, Clone)]
pub enum AttestationEvidence {
    /// No evidence (software-only).
    None,
    /// TPM quote evidence.
    Tpm(TpmQuote),
    /// HSM attestation evidence.
    Hsm(HsmAttestation),
    /// TEE/Enclave attestation evidence.
    Tee(TeeAttestation),
}

/// Attestation verifier for hardware root of trust.
pub struct AttestationVerifier {
    /// Trusted measurements (PCR values, enclave hashes) indexed by type.
    trusted_measurements: Vec<(AttestationType, Vec<u8>)>,
    /// Maximum age of an attestation quote (seconds).
    max_quote_age: f64,
}

impl AttestationVerifier {
    /// Create a new attestation verifier with default settings.
    pub fn new() -> Self {
        Self {
            trusted_measurements: Vec::new(),
            max_quote_age: 300.0, // 5 minutes
        }
    }

    /// Create with custom max quote age.
    pub fn with_max_quote_age(max_age: f64) -> Self {
        Self {
            trusted_measurements: Vec::new(),
            max_quote_age: max_age,
        }
    }

    /// Register a trusted measurement for verification.
    pub fn register_trusted_measurement(
        &mut self,
        att_type: AttestationType,
        measurement: Vec<u8>,
    ) {
        self.trusted_measurements.push((att_type, measurement));
    }

    /// Verify attestation evidence.
    pub fn verify(
        &self,
        evidence: &AttestationEvidence,
        timestamp: f64,
    ) -> AttestationVerification {
        match evidence {
            AttestationEvidence::None => AttestationVerification {
                is_valid: true,
                attestation_type: AttestationType::None,
                measurement: vec![],
                timestamp,
                details: "No attestation required (software-only).".to_string(),
            },
            AttestationEvidence::Tpm(quote) => self.verify_tpm_quote(quote, timestamp),
            AttestationEvidence::Hsm(att) => self.verify_hsm_attestation(att, timestamp),
            AttestationEvidence::Tee(tee) => self.verify_tee_attestation(tee, timestamp),
        }
    }

    /// Verify a TPM 2.0 quote.
    fn verify_tpm_quote(&self, quote: &TpmQuote, timestamp: f64) -> AttestationVerification {
        // Verify quote structure
        if quote.quote_data.is_empty() || quote.pcr_values.is_empty() || quote.signature.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "Invalid TPM quote structure".to_string(),
            };
        }

        // #5 FIX: Verify freshness binding — nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session
        // and prevents replay of captured attestations.
        if quote.nonce.is_empty()
            || quote.channel_binding.is_empty()
            || quote.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Tpm,
                measurement: vec![],
                timestamp,
                details: "TPM quote missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age — rejects stale quotes beyond max_quote_age.
        // A quote_timestamp of 0.0 means the TPM did not embed a timestamp, in
        // which case the age check is skipped (backward compatibility with
        // stubs that do not produce real quotes).
        let age_valid = if quote.quote_timestamp > 0.0 {
            let age = timestamp - quote.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!("TPM quote timestamp is in the future (skew {}s)", -age),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Tpm,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TPM quote expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
            true
        } else {
            false
        };

        // Verify PCR values against trusted measurements
        let pcr_valid = self
            .trusted_measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Tpm
            && m.len() == quote.pcr_values.len()
            && crate::security::constant_time_eq(m, &quote.pcr_values));

        // #5 FIX: Verify signature over quote data INCLUDING the freshness binding.
        // The signature must cover nonce || channel_binding || suite_transcript_hash || quote_data || pcr_values.
        let sig_input = Self::compute_quote_digest(
            &quote.quote_data,
            &quote.pcr_values,
            &quote.nonce,
            &quote.channel_binding,
            &quote.suite_transcript_hash,
        );
        // Cryptographic Ed25519 verification against the AIK public key.
        // Rejects any payload whose signature was not produced by the private key
        // corresponding to quote.aik_public — including replays, fabrications,
        // and any 64-byte blob that is not a valid signature over sig_input.
        let sig_valid = Self::verify_ed25519_signature(
            &quote.aik_public,
            &sig_input,
            &quote.signature,
        );

        AttestationVerification {
            is_valid: pcr_valid && sig_valid,
            attestation_type: AttestationType::Tpm,
            measurement: quote.pcr_values.clone(),
            timestamp,
            details: format!(
                "TPM quote verification: PCR match={}, signature valid={}, freshness bound={}, age_valid={}",
                pcr_valid, sig_valid, !quote.nonce.is_empty(), age_valid
            ),
        }
    }

    /// Verify an HSM attestation.
    fn verify_hsm_attestation(
        &self,
        att: &HsmAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Verify key attestation structure
        if att.key_attestation.is_empty() {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Hsm,
                measurement: vec![],
                timestamp,
                details: "Invalid HSM attestation structure".to_string(),
            };
        }

        // Verify manufacturer certificate chain (simplified)
        let cert_valid = !att.manufacturer_cert.is_empty();

        AttestationVerification {
            is_valid: cert_valid,
            attestation_type: AttestationType::Hsm,
            measurement: att.key_attestation.clone(),
            timestamp,
            details: format!(
                "HSM attestation verification: token={}, cert valid={}",
                att.token_label, cert_valid
            ),
        }
    }

    /// Verify a TEE/Enclave attestation.
    fn verify_tee_attestation(
        &self,
        tee: &TeeAttestation,
        timestamp: f64,
    ) -> AttestationVerification {
        // Verify measurement against trusted values
        let measurement_valid = self
            .trusted_measurements
            .iter()
            .any(|(t, m)| *t == AttestationType::Enclave
            && m.len() == tee.measurement.len()
            && crate::security::constant_time_eq(m, &tee.measurement));

        // #5 FIX: Verify freshness binding — nonce + channel_binding + suite_transcript_hash
        // must be present and non-empty. This binds the quote to this specific session.
        if tee.nonce.is_empty()
            || tee.channel_binding.is_empty()
            || tee.suite_transcript_hash.is_empty()
        {
            return AttestationVerification {
                is_valid: false,
                attestation_type: AttestationType::Enclave,
                measurement: vec![],
                timestamp,
                details: "TEE attestation missing freshness binding (nonce/channel/transcript)"
                    .to_string(),
            };
        }

        // #5 FIX: Verify quote age — rejects stale TEE reports beyond max_quote_age.
        // A quote_timestamp of 0.0 means no timestamp was provided; skip the check.
        if tee.quote_timestamp > 0.0 {
            let age = timestamp - tee.quote_timestamp;
            if age < 0.0 {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation timestamp is in the future (skew {}s)",
                        -age
                    ),
                };
            }
            if age > self.max_quote_age {
                return AttestationVerification {
                    is_valid: false,
                    attestation_type: AttestationType::Enclave,
                    measurement: vec![],
                    timestamp,
                    details: format!(
                        "TEE attestation expired: age {}s exceeds max_quote_age {}s",
                        age, self.max_quote_age
                    ),
                };
            }
        }

        // Verify signature over TEE report digest INCLUDING freshness binding.
        // The signing_public_key must be the exact TEE manufacturer or quoting enclave key.
        // Any empty blob, random bytes, or wrong-key signature is rejected cryptographically.
        let tee_digest = Self::compute_tee_report_digest(
            &tee.measurement,
            &tee.report_data,
            &tee.nonce,
            &tee.channel_binding,
            &tee.suite_transcript_hash,
        );
        let sig_valid = Self::verify_ed25519_signature(
            &tee.signing_public_key,
            &tee_digest,
            &tee.signature,
        );

        AttestationVerification {
            is_valid: measurement_valid && sig_valid,
            attestation_type: AttestationType::Enclave,
            measurement: tee.measurement.clone(),
            timestamp,
            details: format!(
                "TEE attestation verification: measurement valid={}, signature valid={}, freshness bound={}",
                measurement_valid, sig_valid, !tee.nonce.is_empty()
            ),
        }
    }

    /// Compute the digest of a TPM quote for signature verification.
    /// #5 FIX: Includes freshness binding (nonce, channel_binding, suite_transcript_hash)
    /// in the digest so the signature covers the full session context.
    fn compute_quote_digest(
        quote_data: &[u8],
        pcr_values: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-TPM-quote-digest-v2");
        // #5 FIX: Include freshness binding in the digest
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        hasher.update((quote_data.len() as u32).to_be_bytes());
        hasher.update(quote_data);
        hasher.update((pcr_values.len() as u32).to_be_bytes());
        hasher.update(pcr_values);
        hasher.finalize().to_vec()
    }

    /// Compute the digest of a TEE attestation report for signature verification.
    ///
    /// Includes freshness binding (nonce, channel_binding, suite_transcript_hash)
    /// so the signature covers the full session context and cannot be replayed.
    ///
    /// `pub(crate)` so that test helpers can produce correctly-signed reports.
    pub(crate) fn compute_tee_report_digest(
        measurement: &[u8],
        report_data: &[u8],
        nonce: &[u8],
        channel_binding: &[u8],
        suite_transcript_hash: &[u8],
    ) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"SAACP-TEE-report-digest-v1");
        // Freshness binding — length-prefixed to prevent extension attacks
        hasher.update((nonce.len() as u32).to_be_bytes());
        hasher.update(nonce);
        hasher.update((channel_binding.len() as u32).to_be_bytes());
        hasher.update(channel_binding);
        hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
        hasher.update(suite_transcript_hash);
        // Report payload
        hasher.update((measurement.len() as u32).to_be_bytes());
        hasher.update(measurement);
        hasher.update((report_data.len() as u32).to_be_bytes());
        hasher.update(report_data);
        hasher.finalize().to_vec()
    }

    /// Verify an Ed25519 signature over a message using a raw 32-byte public key.
    ///
    /// Returns `false` — never panics — on any of:
    /// - `public_key_bytes` is not exactly 32 bytes
    /// - `signature_bytes` is not exactly 64 bytes
    /// - the key bytes do not represent a valid compressed Ed25519 point
    /// - the signature does not verify against the key and message
    ///
    /// `pub(crate)` so the test submodule can exercise it directly.
    pub(crate) fn verify_ed25519_signature(
        public_key_bytes: &[u8],
        message: &[u8],
        signature_bytes: &[u8],
    ) -> bool {
        // Parse public key — must be exactly 32 bytes
        let pk_array: [u8; 32] = match public_key_bytes.try_into() {
            Ok(a) => a,
            Err(_) => return false,
        };
        let verifying_key = match VerifyingKey::from_bytes(&pk_array) {
            Ok(vk) => vk,
            Err(_) => return false,
        };
        // Parse signature — must be exactly 64 bytes
        let sig_array: [u8; 64] = match signature_bytes.try_into() {
            Ok(a) => a,
            Err(_) => return false,
        };
        let signature = Signature::from_bytes(&sig_array);
        // Cryptographic verification — the only accepted path to `true`
        verifying_key.verify(message, &signature).is_ok()
    }
}

impl Default for AttestationVerifier {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate an attestation challenge for a peer.
/// The challenge is a nonce that the peer must include in its attestation.
pub fn generate_attestation_challenge() -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    challenge
}

/// Verify an attestation challenge response.
pub fn verify_challenge_response(
    challenge: &[u8],
    response: &[u8],
    expected_binding: &[u8],
) -> bool {
    // Response should be HMAC(challenge, binding)
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let mut mac = match HmacSha256::new_from_slice(expected_binding) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(challenge);
    let expected = mac.finalize().into_bytes();
    crate::security::constant_time_eq(response, &expected)
}

/// Create an attestation binding that ties a keypair to hardware.
/// #5 FIX: Includes nonce and channel_binding to bind the attestation to a specific session.
pub fn create_attestation_binding(
    public_key: &[u8],
    measurement: &[u8],
    attestation_type: AttestationType,
    nonce: &[u8],
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    let mut hasher = Sha256::new();
    hasher.update(domain_separation::ATTESTATION_CHALLENGE);
    // #5 FIX: Include freshness binding in the attestation binding
    hasher.update((nonce.len() as u32).to_be_bytes());
    hasher.update(nonce);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.update(public_key);
    hasher.update(measurement);
    hasher.update(attestation_type.as_str().as_bytes());
    hasher.finalize().to_vec()
}

/// #5 FIX: Create a fresh attestation challenge that includes the channel binding
/// and suite transcript hash. This ensures the attestation is bound to this specific
/// session and cannot be replayed.
pub fn create_fresh_attestation_challenge(
    channel_binding: &[u8],
    suite_transcript_hash: &[u8],
) -> Vec<u8> {
    use rand::RngCore;
    let mut challenge = vec![0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut challenge);
    // Bind the challenge to the session context
    let mut hasher = Sha256::new();
    hasher.update(b"SAACP-attestation-challenge-v2");
    hasher.update(&challenge);
    hasher.update((channel_binding.len() as u32).to_be_bytes());
    hasher.update(channel_binding);
    hasher.update((suite_transcript_hash.len() as u32).to_be_bytes());
    hasher.update(suite_transcript_hash);
    hasher.finalize().to_vec()
}

/// Maximum attestation quote size (bytes).
pub const MAX_ATTESTATION_QUOTE_SIZE: usize = max_sizes::MAX_ATTESTATION_QUOTE;

/// Validate attestation quote size to prevent DoS.
pub fn validate_attestation_size(quote_size: usize) -> Result<(), PqcError> {
    if quote_size > MAX_ATTESTATION_QUOTE_SIZE {
        return Err(PqcError::InvalidLength(format!(
            "Attestation quote exceeds maximum size: {} > {}",
            quote_size, MAX_ATTESTATION_QUOTE_SIZE
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::Signer;

    /// Generate a random Ed25519 signing keypair for tests.
    fn test_keypair() -> ed25519_dalek::SigningKey {
        ed25519_dalek::SigningKey::generate(&mut rand::rngs::OsRng)
    }

    /// Build a correctly-signed TpmQuote for the given signing key.
    fn make_valid_tpm_quote(sk: &ed25519_dalek::SigningKey) -> TpmQuote {
        let quote_data = vec![1u8; 100];
        let pcr_values = vec![1u8; 32];
        let nonce = vec![1u8; 32];
        let channel_binding = vec![2u8; 32];
        let suite_transcript_hash = vec![3u8; 32];
        let digest = AttestationVerifier::compute_quote_digest(
            &quote_data, &pcr_values, &nonce, &channel_binding, &suite_transcript_hash,
        );
        let signature: ed25519_dalek::Signature = sk.sign(&digest);
        TpmQuote {
            quote_data,
            pcr_values,
            signature: signature.to_bytes().to_vec(),
            aik_public: sk.verifying_key().to_bytes().to_vec(),
            nonce,
            channel_binding,
            suite_transcript_hash,
            quote_timestamp: 0.0,
        }
    }

    /// Build a correctly-signed TeeAttestation for the given signing key.
    fn make_valid_tee_attest(sk: &ed25519_dalek::SigningKey) -> TeeAttestation {
        let measurement = vec![7u8; 32];
        let report_data = vec![8u8; 64];
        let nonce = vec![4u8; 32];
        let channel_binding = vec![5u8; 32];
        let suite_transcript_hash = vec![6u8; 32];
        let digest = AttestationVerifier::compute_tee_report_digest(
            &measurement, &report_data, &nonce, &channel_binding, &suite_transcript_hash,
        );
        let signature: ed25519_dalek::Signature = sk.sign(&digest);
        TeeAttestation {
            measurement,
            report_data,
            signature: signature.to_bytes().to_vec(),
            tee_type: "sgx".to_string(),
            signing_public_key: sk.verifying_key().to_bytes().to_vec(),
            nonce,
            channel_binding,
            suite_transcript_hash,
            quote_timestamp: 0.0,
        }
    }

    #[test]
    fn test_attestation_type_strings() {
        assert_eq!(AttestationType::None.as_str(), "none");
        assert_eq!(AttestationType::from_str("tpm"), Some(AttestationType::Tpm));
        assert!(AttestationType::Tpm.requires_hardware());
        assert!(!AttestationType::None.requires_hardware());
    }

    #[test]
    fn test_attestation_verifier_none() {
        let verifier = AttestationVerifier::new();
        let result = verifier.verify(&AttestationEvidence::None, 0.0);
        assert!(result.is_valid);
    }

    #[test]
    fn test_attestation_challenge() {
        let challenge = generate_attestation_challenge();
        assert_eq!(challenge.len(), 32);
    }

    #[test]
    fn test_attestation_binding() {
        let nonce = vec![1u8; 32];
        let channel_binding = vec![2u8; 32];
        let suite_transcript_hash = vec![3u8; 32];
        let binding = create_attestation_binding(
            b"pubkey",
            b"measurement",
            AttestationType::Tpm,
            &nonce,
            &channel_binding,
            &suite_transcript_hash,
        );
        assert_eq!(binding.len(), 32);
    }

    #[test]
    fn test_validate_attestation_size() {
        assert!(validate_attestation_size(1000).is_ok());
        assert!(validate_attestation_size(max_sizes::MAX_ATTESTATION_QUOTE + 1).is_err());
    }

    // ── TPM tests ─────────────────────────────────────────────────────────

    #[test]
    fn test_tpm_quote_valid_signature_accepted() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        let quote = make_valid_tpm_quote(&sk);
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(result.is_valid, "Valid TPM quote must be accepted");
    }

    /// Previously the placeholder `len >= 64` would have accepted this.
    #[test]
    fn test_tpm_quote_wrong_aik_rejected() {
        let signing_key = test_keypair();
        let wrong_key = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        let mut quote = make_valid_tpm_quote(&signing_key);
        quote.aik_public = wrong_key.verifying_key().to_bytes().to_vec();
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(!result.is_valid, "TPM quote with wrong AIK must be rejected");
    }

    #[test]
    fn test_tpm_quote_zeros_sig_rejected() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        let mut quote = make_valid_tpm_quote(&sk);
        quote.signature = vec![0u8; 64];
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(!result.is_valid, "Zero-filled TPM signature must be rejected");
    }

    #[test]
    fn test_tpm_quote_tampered_data_rejected() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        let mut quote = make_valid_tpm_quote(&sk);
        quote.quote_data[0] ^= 0xFF;
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(!result.is_valid, "Tampered TPM quote_data must be rejected");
    }

    #[test]
    fn test_tpm_quote_without_freshness_rejected() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Tpm, vec![1u8; 32]);
        let mut quote = make_valid_tpm_quote(&sk);
        quote.nonce = vec![];
        quote.channel_binding = vec![];
        quote.suite_transcript_hash = vec![];
        let result = verifier.verify(&AttestationEvidence::Tpm(quote), 0.0);
        assert!(!result.is_valid, "TPM quote without freshness binding must be rejected");
    }

    // ── TEE tests ─────────────────────────────────────────────────────────

    #[test]
    fn test_tee_attestation_valid_accepted() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![7u8; 32]);
        let attest = make_valid_tee_attest(&sk);
        let result = verifier.verify(&AttestationEvidence::Tee(attest), 0.0);
        assert!(result.is_valid, "Valid TEE attestation must be accepted");
    }

    /// Previously the placeholder `!is_empty()` would have accepted this.
    #[test]
    fn test_tee_attestation_empty_sig_rejected() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![7u8; 32]);
        let mut attest = make_valid_tee_attest(&sk);
        attest.signature = vec![];
        let result = verifier.verify(&AttestationEvidence::Tee(attest), 0.0);
        assert!(!result.is_valid, "Empty TEE signature must be rejected");
    }

    #[test]
    fn test_tee_attestation_wrong_key_rejected() {
        let signing_key = test_keypair();
        let wrong_key = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![7u8; 32]);
        let mut attest = make_valid_tee_attest(&signing_key);
        attest.signing_public_key = wrong_key.verifying_key().to_bytes().to_vec();
        let result = verifier.verify(&AttestationEvidence::Tee(attest), 0.0);
        assert!(!result.is_valid, "TEE attestation with wrong signing key must be rejected");
    }

    #[test]
    fn test_tee_attestation_tampered_measurement_rejected() {
        let sk = test_keypair();
        let mut verifier = AttestationVerifier::new();
        verifier.register_trusted_measurement(AttestationType::Enclave, vec![7u8; 32]);
        let mut attest = make_valid_tee_attest(&sk);
        attest.measurement[0] ^= 0xFF;
        let result = verifier.verify(&AttestationEvidence::Tee(attest), 0.0);
        assert!(!result.is_valid, "Tampered TEE measurement must be rejected");
    }

    // ── verify_ed25519_signature unit tests ──────────────────────────────────

    #[test]
    fn test_verify_ed25519_valid() {
        let sk = test_keypair();
        let msg = b"test message";
        let sig: ed25519_dalek::Signature = sk.sign(msg);
        assert!(
            AttestationVerifier::verify_ed25519_signature(&sk.verifying_key().to_bytes(), msg, &sig.to_bytes()),
            "Genuine Ed25519 signature must verify"
        );
    }

    #[test]
    fn test_verify_ed25519_wrong_message_rejected() {
        let sk = test_keypair();
        let sig: ed25519_dalek::Signature = sk.sign(b"original message");
        assert!(
            !AttestationVerifier::verify_ed25519_signature(
                &sk.verifying_key().to_bytes(), b"different message", &sig.to_bytes()
            ),
            "Signature over different message must be rejected"
        );
    }

    #[test]
    fn test_verify_ed25519_short_key_rejected() {
        assert!(
            !AttestationVerifier::verify_ed25519_signature(&[0u8; 31], b"msg", &[0u8; 64]),
            "Short public key must be rejected"
        );
    }

    #[test]
    fn test_verify_ed25519_short_sig_rejected() {
        let sk = test_keypair();
        assert!(
            !AttestationVerifier::verify_ed25519_signature(&sk.verifying_key().to_bytes(), b"msg", &[0u8; 63]),
            "Short signature must be rejected"
        );
    }
}
